### ISSUE TITLE
Extract configuration settings

### ISSUE THREAD

**Issue by paraenggu** [radiorabe/nowplaying#11]
Extract configuration strings out of the main code and add them to either a configuration file, or load them via environment variables. Using environment variables would make it easier to run the code within container based environments.

**Comment by hairmare** [comment]
I have something based on configargparse prepared that will fix this issue. I'm waiting for #30 and #31 to get merged so I can contribute it.

**Comment by hairmare** [comment]
The leg work for both env variables and config files where merged in #35. IMO the work there should cover all cases.
