### ISSUE TITLE
Remove internal host names and IP addresses

### ISSUE THREAD

**Issue by paraenggu** [radiorabe/nowplaying#9]
Remove the various host names and IP addresses and replace them with environment variables or names / IPs reserved for documentation purpose (such as [example.com](https://tools.ietf.org/html/rfc2606#section-3) and [192.0.2.0/24](https://tools.ietf.org/html/rfc5737#section-3)).

**Comment by hairmare** [comment]
The leg work for this is in #35.

There is also a ton of RaBe specific strings sprinkled throughout the code base. We should take care of those by moving them to config as well.

I think the main focus here should be to not expose secrets in this codebase as well as ensuring that we can override options in production without needing to patch the code. While I :+1: this issue I don't personally think it's all too important at this stage.
